USE [master]
GO

/****** Object:  Database [Sales Data]    Script Date: 5/7/2023 5:19:00 PM ******/
CREATE DATABASE [Sales Data]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sales Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Sales Data.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sales Data_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Sales Data_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sales Data].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Sales Data] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Sales Data] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Sales Data] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Sales Data] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Sales Data] SET ARITHABORT OFF 
GO

ALTER DATABASE [Sales Data] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Sales Data] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Sales Data] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Sales Data] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Sales Data] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Sales Data] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Sales Data] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Sales Data] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Sales Data] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Sales Data] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Sales Data] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Sales Data] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Sales Data] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Sales Data] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Sales Data] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Sales Data] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Sales Data] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Sales Data] SET RECOVERY FULL 
GO

ALTER DATABASE [Sales Data] SET  MULTI_USER 
GO

ALTER DATABASE [Sales Data] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Sales Data] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Sales Data] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Sales Data] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Sales Data] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Sales Data] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Sales Data] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Sales Data] SET  READ_WRITE 
GO


